total_steps: 500000    # 500K training steps
steps_per_epoch: 10000
max_ep_len: 1000
evaluation: False

setting:
  frame_stack: 3
  num_sources: 2
  background_dataset_path: "/opt/rl/dataset/DAVIS/JPEGImages/480p"
  difficulty: 'hard'
  distract_mode: 'train'
  color_scale: 0.1
  test_color_scale: 0.5
  camera_scale: 0.1
  test_camera_scale: 0.3
  num_videos: 1

buffer_params:
  image_size: 84
  capacity: 100000    # 1e5
  nstep: 1 # DEFAULT 
  nstep_rew: 5
  gamma: 0.99
  lambd: 0.9
  save_buffer: False

agent_base_params:
  num: 2
  actor_update_freq: 1
  update_to_data: 1
  update_to_actor: 1
  critic_target_update_freq: 2

extr_params:
  num_layers: 4
  num_filters: 32
  num_fc: 2
  extr_latent_dim: 50
  extr_tau: 0.05
  targ_extr: False

agent_params:
  extr_lr: 5.e-4
  critic_lr: 5.e-4
  critic_beta: 0.9
  actor_lr: 5.e-4
  actor_beta: 0.9
  alpha_lr: 5.e-4
  alpha_beta: 0.5
  actor_mode: 'max'
  image_pad: 4
  update_to_extr: 1
  update_to_data: 1
  update_to_actor: 1
  extr_q_update_freq: ~

algo_params:
  critic_tau: 0.01
  num_q: 2
  num_targ_q: 2
  hidden_dim: 1024
  l: 2        # The num of hidden layer
  extr_latent_dim: 50
  nstep_rew: 5
  cfun: False

train_params:
  init_steps: 1000
  action_repeat: 4
  eval_freq: ~
  test: True
  num_eval_episodes: 10
  save_model: True